// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/messages.proto

package fr.membrives.etienne.remote;

public final class RemoteProtos {
  private RemoteProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CommandOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string source = 1;
    /**
     * <code>optional string source = 1;</code>
     */
    boolean hasSource();
    /**
     * <code>optional string source = 1;</code>
     */
    java.lang.String getSource();
    /**
     * <code>optional string source = 1;</code>
     */
    com.google.protobuf.ByteString
        getSourceBytes();

    // optional .tutorial.Command.CommandType type = 2;
    /**
     * <code>optional .tutorial.Command.CommandType type = 2;</code>
     */
    boolean hasType();
    /**
     * <code>optional .tutorial.Command.CommandType type = 2;</code>
     */
    fr.membrives.etienne.remote.RemoteProtos.Command.CommandType getType();

    // optional string command = 3;
    /**
     * <code>optional string command = 3;</code>
     */
    boolean hasCommand();
    /**
     * <code>optional string command = 3;</code>
     */
    java.lang.String getCommand();
    /**
     * <code>optional string command = 3;</code>
     */
    com.google.protobuf.ByteString
        getCommandBytes();
  }
  /**
   * Protobuf type {@code tutorial.Command}
   */
  public static final class Command extends
      com.google.protobuf.GeneratedMessage
      implements CommandOrBuilder {
    // Use Command.newBuilder() to construct.
    private Command(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Command(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Command defaultInstance;
    public static Command getDefaultInstance() {
      return defaultInstance;
    }

    public Command getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Command(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              source_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              fr.membrives.etienne.remote.RemoteProtos.Command.CommandType value = fr.membrives.etienne.remote.RemoteProtos.Command.CommandType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                type_ = value;
              }
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              command_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fr.membrives.etienne.remote.RemoteProtos.internal_static_tutorial_Command_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fr.membrives.etienne.remote.RemoteProtos.internal_static_tutorial_Command_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fr.membrives.etienne.remote.RemoteProtos.Command.class, fr.membrives.etienne.remote.RemoteProtos.Command.Builder.class);
    }

    public static com.google.protobuf.Parser<Command> PARSER =
        new com.google.protobuf.AbstractParser<Command>() {
      public Command parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Command(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Command> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code tutorial.Command.CommandType}
     */
    public enum CommandType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>STATUS = 1;</code>
       */
      STATUS(0, 1),
      /**
       * <code>COMMAND = 2;</code>
       */
      COMMAND(1, 2),
      /**
       * <code>SPECIAL = 3;</code>
       */
      SPECIAL(2, 3),
      ;

      /**
       * <code>STATUS = 1;</code>
       */
      public static final int STATUS_VALUE = 1;
      /**
       * <code>COMMAND = 2;</code>
       */
      public static final int COMMAND_VALUE = 2;
      /**
       * <code>SPECIAL = 3;</code>
       */
      public static final int SPECIAL_VALUE = 3;


      public final int getNumber() { return value; }

      public static CommandType valueOf(int value) {
        switch (value) {
          case 1: return STATUS;
          case 2: return COMMAND;
          case 3: return SPECIAL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CommandType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CommandType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CommandType>() {
              public CommandType findValueByNumber(int number) {
                return CommandType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return fr.membrives.etienne.remote.RemoteProtos.Command.getDescriptor().getEnumTypes().get(0);
      }

      private static final CommandType[] VALUES = values();

      public static CommandType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private CommandType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:tutorial.Command.CommandType)
    }

    private int bitField0_;
    // optional string source = 1;
    public static final int SOURCE_FIELD_NUMBER = 1;
    private java.lang.Object source_;
    /**
     * <code>optional string source = 1;</code>
     */
    public boolean hasSource() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string source = 1;</code>
     */
    public java.lang.String getSource() {
      java.lang.Object ref = source_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          source_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string source = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSourceBytes() {
      java.lang.Object ref = source_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        source_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional .tutorial.Command.CommandType type = 2;
    public static final int TYPE_FIELD_NUMBER = 2;
    private fr.membrives.etienne.remote.RemoteProtos.Command.CommandType type_;
    /**
     * <code>optional .tutorial.Command.CommandType type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .tutorial.Command.CommandType type = 2;</code>
     */
    public fr.membrives.etienne.remote.RemoteProtos.Command.CommandType getType() {
      return type_;
    }

    // optional string command = 3;
    public static final int COMMAND_FIELD_NUMBER = 3;
    private java.lang.Object command_;
    /**
     * <code>optional string command = 3;</code>
     */
    public boolean hasCommand() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string command = 3;</code>
     */
    public java.lang.String getCommand() {
      java.lang.Object ref = command_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          command_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string command = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCommandBytes() {
      java.lang.Object ref = command_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        command_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      source_ = "";
      type_ = fr.membrives.etienne.remote.RemoteProtos.Command.CommandType.STATUS;
      command_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSourceBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, type_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getCommandBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSourceBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getCommandBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static fr.membrives.etienne.remote.RemoteProtos.Command parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Command parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Command parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Command parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Command parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Command parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Command parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Command parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Command parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Command parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(fr.membrives.etienne.remote.RemoteProtos.Command prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Command}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements fr.membrives.etienne.remote.RemoteProtos.CommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fr.membrives.etienne.remote.RemoteProtos.internal_static_tutorial_Command_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fr.membrives.etienne.remote.RemoteProtos.internal_static_tutorial_Command_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fr.membrives.etienne.remote.RemoteProtos.Command.class, fr.membrives.etienne.remote.RemoteProtos.Command.Builder.class);
      }

      // Construct using fr.membrives.etienne.remote.RemoteProtos.Command.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        source_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = fr.membrives.etienne.remote.RemoteProtos.Command.CommandType.STATUS;
        bitField0_ = (bitField0_ & ~0x00000002);
        command_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fr.membrives.etienne.remote.RemoteProtos.internal_static_tutorial_Command_descriptor;
      }

      public fr.membrives.etienne.remote.RemoteProtos.Command getDefaultInstanceForType() {
        return fr.membrives.etienne.remote.RemoteProtos.Command.getDefaultInstance();
      }

      public fr.membrives.etienne.remote.RemoteProtos.Command build() {
        fr.membrives.etienne.remote.RemoteProtos.Command result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public fr.membrives.etienne.remote.RemoteProtos.Command buildPartial() {
        fr.membrives.etienne.remote.RemoteProtos.Command result = new fr.membrives.etienne.remote.RemoteProtos.Command(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.source_ = source_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.command_ = command_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fr.membrives.etienne.remote.RemoteProtos.Command) {
          return mergeFrom((fr.membrives.etienne.remote.RemoteProtos.Command)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fr.membrives.etienne.remote.RemoteProtos.Command other) {
        if (other == fr.membrives.etienne.remote.RemoteProtos.Command.getDefaultInstance()) return this;
        if (other.hasSource()) {
          bitField0_ |= 0x00000001;
          source_ = other.source_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasCommand()) {
          bitField0_ |= 0x00000004;
          command_ = other.command_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        fr.membrives.etienne.remote.RemoteProtos.Command parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (fr.membrives.etienne.remote.RemoteProtos.Command) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string source = 1;
      private java.lang.Object source_ = "";
      /**
       * <code>optional string source = 1;</code>
       */
      public boolean hasSource() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string source = 1;</code>
       */
      public java.lang.String getSource() {
        java.lang.Object ref = source_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          source_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string source = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSourceBytes() {
        java.lang.Object ref = source_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          source_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string source = 1;</code>
       */
      public Builder setSource(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        source_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string source = 1;</code>
       */
      public Builder clearSource() {
        bitField0_ = (bitField0_ & ~0x00000001);
        source_ = getDefaultInstance().getSource();
        onChanged();
        return this;
      }
      /**
       * <code>optional string source = 1;</code>
       */
      public Builder setSourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        source_ = value;
        onChanged();
        return this;
      }

      // optional .tutorial.Command.CommandType type = 2;
      private fr.membrives.etienne.remote.RemoteProtos.Command.CommandType type_ = fr.membrives.etienne.remote.RemoteProtos.Command.CommandType.STATUS;
      /**
       * <code>optional .tutorial.Command.CommandType type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .tutorial.Command.CommandType type = 2;</code>
       */
      public fr.membrives.etienne.remote.RemoteProtos.Command.CommandType getType() {
        return type_;
      }
      /**
       * <code>optional .tutorial.Command.CommandType type = 2;</code>
       */
      public Builder setType(fr.membrives.etienne.remote.RemoteProtos.Command.CommandType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .tutorial.Command.CommandType type = 2;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = fr.membrives.etienne.remote.RemoteProtos.Command.CommandType.STATUS;
        onChanged();
        return this;
      }

      // optional string command = 3;
      private java.lang.Object command_ = "";
      /**
       * <code>optional string command = 3;</code>
       */
      public boolean hasCommand() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string command = 3;</code>
       */
      public java.lang.String getCommand() {
        java.lang.Object ref = command_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          command_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string command = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCommandBytes() {
        java.lang.Object ref = command_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          command_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string command = 3;</code>
       */
      public Builder setCommand(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        command_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string command = 3;</code>
       */
      public Builder clearCommand() {
        bitField0_ = (bitField0_ & ~0x00000004);
        command_ = getDefaultInstance().getCommand();
        onChanged();
        return this;
      }
      /**
       * <code>optional string command = 3;</code>
       */
      public Builder setCommandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        command_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.Command)
    }

    static {
      defaultInstance = new Command(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tutorial.Command)
  }

  public interface ResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .tutorial.Response.FrontendStatus status = 1;
    /**
     * <code>optional .tutorial.Response.FrontendStatus status = 1;</code>
     */
    boolean hasStatus();
    /**
     * <code>optional .tutorial.Response.FrontendStatus status = 1;</code>
     */
    fr.membrives.etienne.remote.RemoteProtos.Response.FrontendStatus getStatus();

    // optional .tutorial.Response.CommandStatus command_status = 2;
    /**
     * <code>optional .tutorial.Response.CommandStatus command_status = 2;</code>
     */
    boolean hasCommandStatus();
    /**
     * <code>optional .tutorial.Response.CommandStatus command_status = 2;</code>
     */
    fr.membrives.etienne.remote.RemoteProtos.Response.CommandStatus getCommandStatus();
  }
  /**
   * Protobuf type {@code tutorial.Response}
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessage
      implements ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Response(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }

    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              fr.membrives.etienne.remote.RemoteProtos.Response.FrontendStatus value = fr.membrives.etienne.remote.RemoteProtos.Response.FrontendStatus.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                status_ = value;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              fr.membrives.etienne.remote.RemoteProtos.Response.CommandStatus value = fr.membrives.etienne.remote.RemoteProtos.Response.CommandStatus.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                commandStatus_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fr.membrives.etienne.remote.RemoteProtos.internal_static_tutorial_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fr.membrives.etienne.remote.RemoteProtos.internal_static_tutorial_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fr.membrives.etienne.remote.RemoteProtos.Response.class, fr.membrives.etienne.remote.RemoteProtos.Response.Builder.class);
    }

    public static com.google.protobuf.Parser<Response> PARSER =
        new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code tutorial.Response.FrontendStatus}
     */
    public enum FrontendStatus
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CONNECTED = 1;</code>
       */
      CONNECTED(0, 1),
      ;

      /**
       * <code>CONNECTED = 1;</code>
       */
      public static final int CONNECTED_VALUE = 1;


      public final int getNumber() { return value; }

      public static FrontendStatus valueOf(int value) {
        switch (value) {
          case 1: return CONNECTED;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<FrontendStatus>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<FrontendStatus>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<FrontendStatus>() {
              public FrontendStatus findValueByNumber(int number) {
                return FrontendStatus.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return fr.membrives.etienne.remote.RemoteProtos.Response.getDescriptor().getEnumTypes().get(0);
      }

      private static final FrontendStatus[] VALUES = values();

      public static FrontendStatus valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private FrontendStatus(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:tutorial.Response.FrontendStatus)
    }

    /**
     * Protobuf enum {@code tutorial.Response.CommandStatus}
     */
    public enum CommandStatus
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SUCCESS = 1;</code>
       */
      SUCCESS(0, 1),
      /**
       * <code>FAILURE = 2;</code>
       */
      FAILURE(1, 2),
      ;

      /**
       * <code>SUCCESS = 1;</code>
       */
      public static final int SUCCESS_VALUE = 1;
      /**
       * <code>FAILURE = 2;</code>
       */
      public static final int FAILURE_VALUE = 2;


      public final int getNumber() { return value; }

      public static CommandStatus valueOf(int value) {
        switch (value) {
          case 1: return SUCCESS;
          case 2: return FAILURE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CommandStatus>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CommandStatus>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CommandStatus>() {
              public CommandStatus findValueByNumber(int number) {
                return CommandStatus.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return fr.membrives.etienne.remote.RemoteProtos.Response.getDescriptor().getEnumTypes().get(1);
      }

      private static final CommandStatus[] VALUES = values();

      public static CommandStatus valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private CommandStatus(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:tutorial.Response.CommandStatus)
    }

    private int bitField0_;
    // optional .tutorial.Response.FrontendStatus status = 1;
    public static final int STATUS_FIELD_NUMBER = 1;
    private fr.membrives.etienne.remote.RemoteProtos.Response.FrontendStatus status_;
    /**
     * <code>optional .tutorial.Response.FrontendStatus status = 1;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .tutorial.Response.FrontendStatus status = 1;</code>
     */
    public fr.membrives.etienne.remote.RemoteProtos.Response.FrontendStatus getStatus() {
      return status_;
    }

    // optional .tutorial.Response.CommandStatus command_status = 2;
    public static final int COMMAND_STATUS_FIELD_NUMBER = 2;
    private fr.membrives.etienne.remote.RemoteProtos.Response.CommandStatus commandStatus_;
    /**
     * <code>optional .tutorial.Response.CommandStatus command_status = 2;</code>
     */
    public boolean hasCommandStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .tutorial.Response.CommandStatus command_status = 2;</code>
     */
    public fr.membrives.etienne.remote.RemoteProtos.Response.CommandStatus getCommandStatus() {
      return commandStatus_;
    }

    private void initFields() {
      status_ = fr.membrives.etienne.remote.RemoteProtos.Response.FrontendStatus.CONNECTED;
      commandStatus_ = fr.membrives.etienne.remote.RemoteProtos.Response.CommandStatus.SUCCESS;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, status_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, commandStatus_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, status_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, commandStatus_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static fr.membrives.etienne.remote.RemoteProtos.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(fr.membrives.etienne.remote.RemoteProtos.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements fr.membrives.etienne.remote.RemoteProtos.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fr.membrives.etienne.remote.RemoteProtos.internal_static_tutorial_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fr.membrives.etienne.remote.RemoteProtos.internal_static_tutorial_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fr.membrives.etienne.remote.RemoteProtos.Response.class, fr.membrives.etienne.remote.RemoteProtos.Response.Builder.class);
      }

      // Construct using fr.membrives.etienne.remote.RemoteProtos.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        status_ = fr.membrives.etienne.remote.RemoteProtos.Response.FrontendStatus.CONNECTED;
        bitField0_ = (bitField0_ & ~0x00000001);
        commandStatus_ = fr.membrives.etienne.remote.RemoteProtos.Response.CommandStatus.SUCCESS;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fr.membrives.etienne.remote.RemoteProtos.internal_static_tutorial_Response_descriptor;
      }

      public fr.membrives.etienne.remote.RemoteProtos.Response getDefaultInstanceForType() {
        return fr.membrives.etienne.remote.RemoteProtos.Response.getDefaultInstance();
      }

      public fr.membrives.etienne.remote.RemoteProtos.Response build() {
        fr.membrives.etienne.remote.RemoteProtos.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public fr.membrives.etienne.remote.RemoteProtos.Response buildPartial() {
        fr.membrives.etienne.remote.RemoteProtos.Response result = new fr.membrives.etienne.remote.RemoteProtos.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.commandStatus_ = commandStatus_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fr.membrives.etienne.remote.RemoteProtos.Response) {
          return mergeFrom((fr.membrives.etienne.remote.RemoteProtos.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fr.membrives.etienne.remote.RemoteProtos.Response other) {
        if (other == fr.membrives.etienne.remote.RemoteProtos.Response.getDefaultInstance()) return this;
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasCommandStatus()) {
          setCommandStatus(other.getCommandStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        fr.membrives.etienne.remote.RemoteProtos.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (fr.membrives.etienne.remote.RemoteProtos.Response) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .tutorial.Response.FrontendStatus status = 1;
      private fr.membrives.etienne.remote.RemoteProtos.Response.FrontendStatus status_ = fr.membrives.etienne.remote.RemoteProtos.Response.FrontendStatus.CONNECTED;
      /**
       * <code>optional .tutorial.Response.FrontendStatus status = 1;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .tutorial.Response.FrontendStatus status = 1;</code>
       */
      public fr.membrives.etienne.remote.RemoteProtos.Response.FrontendStatus getStatus() {
        return status_;
      }
      /**
       * <code>optional .tutorial.Response.FrontendStatus status = 1;</code>
       */
      public Builder setStatus(fr.membrives.etienne.remote.RemoteProtos.Response.FrontendStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .tutorial.Response.FrontendStatus status = 1;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = fr.membrives.etienne.remote.RemoteProtos.Response.FrontendStatus.CONNECTED;
        onChanged();
        return this;
      }

      // optional .tutorial.Response.CommandStatus command_status = 2;
      private fr.membrives.etienne.remote.RemoteProtos.Response.CommandStatus commandStatus_ = fr.membrives.etienne.remote.RemoteProtos.Response.CommandStatus.SUCCESS;
      /**
       * <code>optional .tutorial.Response.CommandStatus command_status = 2;</code>
       */
      public boolean hasCommandStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .tutorial.Response.CommandStatus command_status = 2;</code>
       */
      public fr.membrives.etienne.remote.RemoteProtos.Response.CommandStatus getCommandStatus() {
        return commandStatus_;
      }
      /**
       * <code>optional .tutorial.Response.CommandStatus command_status = 2;</code>
       */
      public Builder setCommandStatus(fr.membrives.etienne.remote.RemoteProtos.Response.CommandStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        commandStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .tutorial.Response.CommandStatus command_status = 2;</code>
       */
      public Builder clearCommandStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        commandStatus_ = fr.membrives.etienne.remote.RemoteProtos.Response.CommandStatus.SUCCESS;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.Response)
    }

    static {
      defaultInstance = new Response(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tutorial.Response)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Command_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_Command_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024proto/messages.proto\022\010tutorial\"\214\001\n\007Com" +
      "mand\022\016\n\006source\030\001 \001(\t\022+\n\004type\030\002 \001(\0162\035.tut" +
      "orial.Command.CommandType\022\017\n\007command\030\003 \001" +
      "(\t\"3\n\013CommandType\022\n\n\006STATUS\020\001\022\013\n\007COMMAND" +
      "\020\002\022\013\n\007SPECIAL\020\003\"\303\001\n\010Response\0221\n\006status\030\001" +
      " \001(\0162!.tutorial.Response.FrontendStatus\022" +
      "8\n\016command_status\030\002 \001(\0162 .tutorial.Respo" +
      "nse.CommandStatus\"\037\n\016FrontendStatus\022\r\n\tC" +
      "ONNECTED\020\001\")\n\rCommandStatus\022\013\n\007SUCCESS\020\001" +
      "\022\013\n\007FAILURE\020\002B+\n\033fr.membrives.etienne.re",
      "moteB\014RemoteProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_tutorial_Command_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_tutorial_Command_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_Command_descriptor,
              new java.lang.String[] { "Source", "Type", "Command", });
          internal_static_tutorial_Response_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_tutorial_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_Response_descriptor,
              new java.lang.String[] { "Status", "CommandStatus", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
