language: go

go:
    - 1.4

before_script:
  - git clone https://github.com/google/leveldb
  - cd leveldb && make && cd ..
  - export PATH=$PATH:$PWD/leveldb
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/leveldb
  - export LIBRARY_PATH=$LIBRARY_PATH:$PWD/leveldb
  - export CPATH=$CPATH:$PWD/leveldb/include

addons:
  apt:
    packages:
      - libleveldb1
      - libleveldb-dev
      - libzmq3
      - libzmq3-dev
      - pkg-config

