language: go

go:
    - 1.4

before_install:
# Leveldb
  - git clone https://github.com/google/leveldb
  - cd leveldb && make && cd ..
  - export PATH=$PATH:$PWD/leveldb
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/leveldb
  - export LIBRARY_PATH=$LIBRARY_PATH:$PWD/leveldb
  - export CPATH=$CPATH:$PWD/leveldb/include
# ZeroMQ
  - wget http://download.zeromq.org/zeromq-4.1.2.tar.gz /tmp/zeromq-4.1.2.tar.gz
  - tar -xvf /tmp/zeromq-4.1.2.tar.gz
  - mkdir /tmp/zeromq
  - cd zeromq-4.1.2 && ./configure --prefix=/tmp/zeromq --exec-prefix=/tmp/zeromq && make && make install && cd ..
  - export PATH=$PATH:/tmp/zeromq/bin
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/tmp/zeromq/lib
  - export LIBRARY_PATH=$LIBRARY_PATH:/tmp/zeromq/lib
  - export CPATH=$CPATH:/tmp/zeromq/include

addons:
  apt:
    packages:
      - pkg-config

