// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

package proto

import proto1 "github.com/golang/protobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto1.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type RequestType int32

const (
	RequestType_SERVICE_DISCOVERY RequestType = 1
	RequestType_WRITE_ENDPOINT    RequestType = 2
)

var RequestType_name = map[int32]string{
	1: "SERVICE_DISCOVERY",
	2: "WRITE_ENDPOINT",
}
var RequestType_value = map[string]int32{
	"SERVICE_DISCOVERY": 1,
	"WRITE_ENDPOINT":    2,
}

func (x RequestType) Enum() *RequestType {
	p := new(RequestType)
	*p = x
	return p
}
func (x RequestType) String() string {
	return proto1.EnumName(RequestType_name, int32(x))
}
func (x RequestType) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *RequestType) UnmarshalJSON(data []byte) error {
	value, err := proto1.UnmarshalJSONEnum(RequestType_value, data, "RequestType")
	if err != nil {
		return err
	}
	*x = RequestType(value)
	return nil
}

type Request struct {
	Type             *RequestType `protobuf:"varint,1,opt,name=type,enum=proto.RequestType" json:"type,omitempty"`
	WriteRequest     []*Endpoint  `protobuf:"bytes,2,rep,name=write_request" json:"write_request,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto1.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

func (m *Request) GetType() RequestType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Request) GetWriteRequest() []*Endpoint {
	if m != nil {
		return m.WriteRequest
	}
	return nil
}

type Endpoint struct {
	Service          *string `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
	Endpoint         *string `protobuf:"bytes,2,opt,name=endpoint" json:"endpoint,omitempty"`
	Value            *string `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Endpoint) Reset()         { *m = Endpoint{} }
func (m *Endpoint) String() string { return proto1.CompactTextString(m) }
func (*Endpoint) ProtoMessage()    {}

func (m *Endpoint) GetService() string {
	if m != nil && m.Service != nil {
		return *m.Service
	}
	return ""
}

func (m *Endpoint) GetEndpoint() string {
	if m != nil && m.Endpoint != nil {
		return *m.Endpoint
	}
	return ""
}

func (m *Endpoint) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type Response struct {
	ErrorMessage     *string     `protobuf:"bytes,1,opt,name=error_message" json:"error_message,omitempty"`
	Endpoints        []*Endpoint `protobuf:"bytes,2,rep,name=endpoints" json:"endpoints,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto1.CompactTextString(m) }
func (*Response) ProtoMessage()    {}

func (m *Response) GetErrorMessage() string {
	if m != nil && m.ErrorMessage != nil {
		return *m.ErrorMessage
	}
	return ""
}

func (m *Response) GetEndpoints() []*Endpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

func init() {
	proto1.RegisterEnum("proto.RequestType", RequestType_name, RequestType_value)
}
