// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

package proto

import proto1 "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto1.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Command_CommandType int32

const (
	Command_COMMAND Command_CommandType = 1
	Command_STATUS  Command_CommandType = 2
)

var Command_CommandType_name = map[int32]string{
	1: "COMMAND",
	2: "STATUS",
}
var Command_CommandType_value = map[string]int32{
	"COMMAND": 1,
	"STATUS":  2,
}

func (x Command_CommandType) Enum() *Command_CommandType {
	p := new(Command_CommandType)
	*p = x
	return p
}
func (x Command_CommandType) String() string {
	return proto1.EnumName(Command_CommandType_name, int32(x))
}
func (x Command_CommandType) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *Command_CommandType) UnmarshalJSON(data []byte) error {
	value, err := proto1.UnmarshalJSONEnum(Command_CommandType_value, data, "Command_CommandType")
	if err != nil {
		return err
	}
	*x = Command_CommandType(value)
	return nil
}

type Command struct {
	Type             *Command_CommandType `protobuf:"varint,1,opt,name=type,enum=proto.Command_CommandType" json:"type,omitempty"`
	Command          *int32               `protobuf:"varint,2,opt,name=command" json:"command,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto1.CompactTextString(m) }
func (*Command) ProtoMessage()    {}

func (m *Command) GetType() Command_CommandType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Command) GetCommand() int32 {
	if m != nil && m.Command != nil {
		return *m.Command
	}
	return 0
}

type Response struct {
	FrontendConnected *bool  `protobuf:"varint,1,opt,name=frontend_connected" json:"frontend_connected,omitempty"`
	XXX_unrecognized  []byte `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto1.CompactTextString(m) }
func (*Response) ProtoMessage()    {}

func (m *Response) GetFrontendConnected() bool {
	if m != nil && m.FrontendConnected != nil {
		return *m.FrontendConnected
	}
	return false
}

func init() {
	proto1.RegisterEnum("proto.Command_CommandType", Command_CommandType_name, Command_CommandType_value)
}
