// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package fr.membrives.etienne.remote;

public final class RemoteProtos {
  private RemoteProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code proto.RequestType}
   */
  public enum RequestType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SERVICE_DISCOVERY = 1;</code>
     */
    SERVICE_DISCOVERY(0, 1),
    /**
     * <code>WRITE_ENDPOINT = 2;</code>
     */
    WRITE_ENDPOINT(1, 2),
    ;

    /**
     * <code>SERVICE_DISCOVERY = 1;</code>
     */
    public static final int SERVICE_DISCOVERY_VALUE = 1;
    /**
     * <code>WRITE_ENDPOINT = 2;</code>
     */
    public static final int WRITE_ENDPOINT_VALUE = 2;


    public final int getNumber() { return value; }

    public static RequestType valueOf(int value) {
      switch (value) {
        case 1: return SERVICE_DISCOVERY;
        case 2: return WRITE_ENDPOINT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<RequestType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
            public RequestType findValueByNumber(int number) {
              return RequestType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return fr.membrives.etienne.remote.RemoteProtos.getDescriptor().getEnumTypes().get(0);
    }

    private static final RequestType[] VALUES = values();

    public static RequestType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private RequestType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proto.RequestType)
  }

  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .proto.RequestType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>optional .proto.RequestType type = 1;</code>
     */
    fr.membrives.etienne.remote.RemoteProtos.RequestType getType();

    /**
     * <code>repeated .proto.Endpoint write_request = 2;</code>
     */
    java.util.List<fr.membrives.etienne.remote.RemoteProtos.Endpoint> 
        getWriteRequestList();
    /**
     * <code>repeated .proto.Endpoint write_request = 2;</code>
     */
    fr.membrives.etienne.remote.RemoteProtos.Endpoint getWriteRequest(int index);
    /**
     * <code>repeated .proto.Endpoint write_request = 2;</code>
     */
    int getWriteRequestCount();
    /**
     * <code>repeated .proto.Endpoint write_request = 2;</code>
     */
    java.util.List<? extends fr.membrives.etienne.remote.RemoteProtos.EndpointOrBuilder> 
        getWriteRequestOrBuilderList();
    /**
     * <code>repeated .proto.Endpoint write_request = 2;</code>
     */
    fr.membrives.etienne.remote.RemoteProtos.EndpointOrBuilder getWriteRequestOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto.Request}
   */
  public static final class Request extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.Request)
      RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }

    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              fr.membrives.etienne.remote.RemoteProtos.RequestType value = fr.membrives.etienne.remote.RemoteProtos.RequestType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                writeRequest_ = new java.util.ArrayList<fr.membrives.etienne.remote.RemoteProtos.Endpoint>();
                mutable_bitField0_ |= 0x00000002;
              }
              writeRequest_.add(input.readMessage(fr.membrives.etienne.remote.RemoteProtos.Endpoint.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          writeRequest_ = java.util.Collections.unmodifiableList(writeRequest_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fr.membrives.etienne.remote.RemoteProtos.internal_static_proto_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fr.membrives.etienne.remote.RemoteProtos.internal_static_proto_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fr.membrives.etienne.remote.RemoteProtos.Request.class, fr.membrives.etienne.remote.RemoteProtos.Request.Builder.class);
    }

    public static com.google.protobuf.Parser<Request> PARSER =
        new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private fr.membrives.etienne.remote.RemoteProtos.RequestType type_;
    /**
     * <code>optional .proto.RequestType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .proto.RequestType type = 1;</code>
     */
    public fr.membrives.etienne.remote.RemoteProtos.RequestType getType() {
      return type_;
    }

    public static final int WRITE_REQUEST_FIELD_NUMBER = 2;
    private java.util.List<fr.membrives.etienne.remote.RemoteProtos.Endpoint> writeRequest_;
    /**
     * <code>repeated .proto.Endpoint write_request = 2;</code>
     */
    public java.util.List<fr.membrives.etienne.remote.RemoteProtos.Endpoint> getWriteRequestList() {
      return writeRequest_;
    }
    /**
     * <code>repeated .proto.Endpoint write_request = 2;</code>
     */
    public java.util.List<? extends fr.membrives.etienne.remote.RemoteProtos.EndpointOrBuilder> 
        getWriteRequestOrBuilderList() {
      return writeRequest_;
    }
    /**
     * <code>repeated .proto.Endpoint write_request = 2;</code>
     */
    public int getWriteRequestCount() {
      return writeRequest_.size();
    }
    /**
     * <code>repeated .proto.Endpoint write_request = 2;</code>
     */
    public fr.membrives.etienne.remote.RemoteProtos.Endpoint getWriteRequest(int index) {
      return writeRequest_.get(index);
    }
    /**
     * <code>repeated .proto.Endpoint write_request = 2;</code>
     */
    public fr.membrives.etienne.remote.RemoteProtos.EndpointOrBuilder getWriteRequestOrBuilder(
        int index) {
      return writeRequest_.get(index);
    }

    private void initFields() {
      type_ = fr.membrives.etienne.remote.RemoteProtos.RequestType.SERVICE_DISCOVERY;
      writeRequest_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      for (int i = 0; i < writeRequest_.size(); i++) {
        output.writeMessage(2, writeRequest_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      for (int i = 0; i < writeRequest_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, writeRequest_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static fr.membrives.etienne.remote.RemoteProtos.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(fr.membrives.etienne.remote.RemoteProtos.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Request)
        fr.membrives.etienne.remote.RemoteProtos.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fr.membrives.etienne.remote.RemoteProtos.internal_static_proto_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fr.membrives.etienne.remote.RemoteProtos.internal_static_proto_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fr.membrives.etienne.remote.RemoteProtos.Request.class, fr.membrives.etienne.remote.RemoteProtos.Request.Builder.class);
      }

      // Construct using fr.membrives.etienne.remote.RemoteProtos.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getWriteRequestFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = fr.membrives.etienne.remote.RemoteProtos.RequestType.SERVICE_DISCOVERY;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (writeRequestBuilder_ == null) {
          writeRequest_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          writeRequestBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fr.membrives.etienne.remote.RemoteProtos.internal_static_proto_Request_descriptor;
      }

      public fr.membrives.etienne.remote.RemoteProtos.Request getDefaultInstanceForType() {
        return fr.membrives.etienne.remote.RemoteProtos.Request.getDefaultInstance();
      }

      public fr.membrives.etienne.remote.RemoteProtos.Request build() {
        fr.membrives.etienne.remote.RemoteProtos.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public fr.membrives.etienne.remote.RemoteProtos.Request buildPartial() {
        fr.membrives.etienne.remote.RemoteProtos.Request result = new fr.membrives.etienne.remote.RemoteProtos.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (writeRequestBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            writeRequest_ = java.util.Collections.unmodifiableList(writeRequest_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.writeRequest_ = writeRequest_;
        } else {
          result.writeRequest_ = writeRequestBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fr.membrives.etienne.remote.RemoteProtos.Request) {
          return mergeFrom((fr.membrives.etienne.remote.RemoteProtos.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fr.membrives.etienne.remote.RemoteProtos.Request other) {
        if (other == fr.membrives.etienne.remote.RemoteProtos.Request.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (writeRequestBuilder_ == null) {
          if (!other.writeRequest_.isEmpty()) {
            if (writeRequest_.isEmpty()) {
              writeRequest_ = other.writeRequest_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureWriteRequestIsMutable();
              writeRequest_.addAll(other.writeRequest_);
            }
            onChanged();
          }
        } else {
          if (!other.writeRequest_.isEmpty()) {
            if (writeRequestBuilder_.isEmpty()) {
              writeRequestBuilder_.dispose();
              writeRequestBuilder_ = null;
              writeRequest_ = other.writeRequest_;
              bitField0_ = (bitField0_ & ~0x00000002);
              writeRequestBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getWriteRequestFieldBuilder() : null;
            } else {
              writeRequestBuilder_.addAllMessages(other.writeRequest_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        fr.membrives.etienne.remote.RemoteProtos.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (fr.membrives.etienne.remote.RemoteProtos.Request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private fr.membrives.etienne.remote.RemoteProtos.RequestType type_ = fr.membrives.etienne.remote.RemoteProtos.RequestType.SERVICE_DISCOVERY;
      /**
       * <code>optional .proto.RequestType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .proto.RequestType type = 1;</code>
       */
      public fr.membrives.etienne.remote.RemoteProtos.RequestType getType() {
        return type_;
      }
      /**
       * <code>optional .proto.RequestType type = 1;</code>
       */
      public Builder setType(fr.membrives.etienne.remote.RemoteProtos.RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .proto.RequestType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = fr.membrives.etienne.remote.RemoteProtos.RequestType.SERVICE_DISCOVERY;
        onChanged();
        return this;
      }

      private java.util.List<fr.membrives.etienne.remote.RemoteProtos.Endpoint> writeRequest_ =
        java.util.Collections.emptyList();
      private void ensureWriteRequestIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          writeRequest_ = new java.util.ArrayList<fr.membrives.etienne.remote.RemoteProtos.Endpoint>(writeRequest_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          fr.membrives.etienne.remote.RemoteProtos.Endpoint, fr.membrives.etienne.remote.RemoteProtos.Endpoint.Builder, fr.membrives.etienne.remote.RemoteProtos.EndpointOrBuilder> writeRequestBuilder_;

      /**
       * <code>repeated .proto.Endpoint write_request = 2;</code>
       */
      public java.util.List<fr.membrives.etienne.remote.RemoteProtos.Endpoint> getWriteRequestList() {
        if (writeRequestBuilder_ == null) {
          return java.util.Collections.unmodifiableList(writeRequest_);
        } else {
          return writeRequestBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.Endpoint write_request = 2;</code>
       */
      public int getWriteRequestCount() {
        if (writeRequestBuilder_ == null) {
          return writeRequest_.size();
        } else {
          return writeRequestBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.Endpoint write_request = 2;</code>
       */
      public fr.membrives.etienne.remote.RemoteProtos.Endpoint getWriteRequest(int index) {
        if (writeRequestBuilder_ == null) {
          return writeRequest_.get(index);
        } else {
          return writeRequestBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.Endpoint write_request = 2;</code>
       */
      public Builder setWriteRequest(
          int index, fr.membrives.etienne.remote.RemoteProtos.Endpoint value) {
        if (writeRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWriteRequestIsMutable();
          writeRequest_.set(index, value);
          onChanged();
        } else {
          writeRequestBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Endpoint write_request = 2;</code>
       */
      public Builder setWriteRequest(
          int index, fr.membrives.etienne.remote.RemoteProtos.Endpoint.Builder builderForValue) {
        if (writeRequestBuilder_ == null) {
          ensureWriteRequestIsMutable();
          writeRequest_.set(index, builderForValue.build());
          onChanged();
        } else {
          writeRequestBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Endpoint write_request = 2;</code>
       */
      public Builder addWriteRequest(fr.membrives.etienne.remote.RemoteProtos.Endpoint value) {
        if (writeRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWriteRequestIsMutable();
          writeRequest_.add(value);
          onChanged();
        } else {
          writeRequestBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Endpoint write_request = 2;</code>
       */
      public Builder addWriteRequest(
          int index, fr.membrives.etienne.remote.RemoteProtos.Endpoint value) {
        if (writeRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWriteRequestIsMutable();
          writeRequest_.add(index, value);
          onChanged();
        } else {
          writeRequestBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Endpoint write_request = 2;</code>
       */
      public Builder addWriteRequest(
          fr.membrives.etienne.remote.RemoteProtos.Endpoint.Builder builderForValue) {
        if (writeRequestBuilder_ == null) {
          ensureWriteRequestIsMutable();
          writeRequest_.add(builderForValue.build());
          onChanged();
        } else {
          writeRequestBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Endpoint write_request = 2;</code>
       */
      public Builder addWriteRequest(
          int index, fr.membrives.etienne.remote.RemoteProtos.Endpoint.Builder builderForValue) {
        if (writeRequestBuilder_ == null) {
          ensureWriteRequestIsMutable();
          writeRequest_.add(index, builderForValue.build());
          onChanged();
        } else {
          writeRequestBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Endpoint write_request = 2;</code>
       */
      public Builder addAllWriteRequest(
          java.lang.Iterable<? extends fr.membrives.etienne.remote.RemoteProtos.Endpoint> values) {
        if (writeRequestBuilder_ == null) {
          ensureWriteRequestIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, writeRequest_);
          onChanged();
        } else {
          writeRequestBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Endpoint write_request = 2;</code>
       */
      public Builder clearWriteRequest() {
        if (writeRequestBuilder_ == null) {
          writeRequest_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          writeRequestBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.Endpoint write_request = 2;</code>
       */
      public Builder removeWriteRequest(int index) {
        if (writeRequestBuilder_ == null) {
          ensureWriteRequestIsMutable();
          writeRequest_.remove(index);
          onChanged();
        } else {
          writeRequestBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Endpoint write_request = 2;</code>
       */
      public fr.membrives.etienne.remote.RemoteProtos.Endpoint.Builder getWriteRequestBuilder(
          int index) {
        return getWriteRequestFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.Endpoint write_request = 2;</code>
       */
      public fr.membrives.etienne.remote.RemoteProtos.EndpointOrBuilder getWriteRequestOrBuilder(
          int index) {
        if (writeRequestBuilder_ == null) {
          return writeRequest_.get(index);  } else {
          return writeRequestBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.Endpoint write_request = 2;</code>
       */
      public java.util.List<? extends fr.membrives.etienne.remote.RemoteProtos.EndpointOrBuilder> 
           getWriteRequestOrBuilderList() {
        if (writeRequestBuilder_ != null) {
          return writeRequestBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(writeRequest_);
        }
      }
      /**
       * <code>repeated .proto.Endpoint write_request = 2;</code>
       */
      public fr.membrives.etienne.remote.RemoteProtos.Endpoint.Builder addWriteRequestBuilder() {
        return getWriteRequestFieldBuilder().addBuilder(
            fr.membrives.etienne.remote.RemoteProtos.Endpoint.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.Endpoint write_request = 2;</code>
       */
      public fr.membrives.etienne.remote.RemoteProtos.Endpoint.Builder addWriteRequestBuilder(
          int index) {
        return getWriteRequestFieldBuilder().addBuilder(
            index, fr.membrives.etienne.remote.RemoteProtos.Endpoint.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.Endpoint write_request = 2;</code>
       */
      public java.util.List<fr.membrives.etienne.remote.RemoteProtos.Endpoint.Builder> 
           getWriteRequestBuilderList() {
        return getWriteRequestFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          fr.membrives.etienne.remote.RemoteProtos.Endpoint, fr.membrives.etienne.remote.RemoteProtos.Endpoint.Builder, fr.membrives.etienne.remote.RemoteProtos.EndpointOrBuilder> 
          getWriteRequestFieldBuilder() {
        if (writeRequestBuilder_ == null) {
          writeRequestBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              fr.membrives.etienne.remote.RemoteProtos.Endpoint, fr.membrives.etienne.remote.RemoteProtos.Endpoint.Builder, fr.membrives.etienne.remote.RemoteProtos.EndpointOrBuilder>(
                  writeRequest_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          writeRequest_ = null;
        }
        return writeRequestBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:proto.Request)
    }

    static {
      defaultInstance = new Request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.Request)
  }

  public interface EndpointOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Endpoint)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string endpoint = 1;</code>
     */
    boolean hasEndpoint();
    /**
     * <code>optional string endpoint = 1;</code>
     */
    java.lang.String getEndpoint();
    /**
     * <code>optional string endpoint = 1;</code>
     */
    com.google.protobuf.ByteString
        getEndpointBytes();

    /**
     * <code>optional string value = 2;</code>
     */
    boolean hasValue();
    /**
     * <code>optional string value = 2;</code>
     */
    java.lang.String getValue();
    /**
     * <code>optional string value = 2;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code proto.Endpoint}
   */
  public static final class Endpoint extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.Endpoint)
      EndpointOrBuilder {
    // Use Endpoint.newBuilder() to construct.
    private Endpoint(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Endpoint(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Endpoint defaultInstance;
    public static Endpoint getDefaultInstance() {
      return defaultInstance;
    }

    public Endpoint getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Endpoint(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              endpoint_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              value_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fr.membrives.etienne.remote.RemoteProtos.internal_static_proto_Endpoint_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fr.membrives.etienne.remote.RemoteProtos.internal_static_proto_Endpoint_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fr.membrives.etienne.remote.RemoteProtos.Endpoint.class, fr.membrives.etienne.remote.RemoteProtos.Endpoint.Builder.class);
    }

    public static com.google.protobuf.Parser<Endpoint> PARSER =
        new com.google.protobuf.AbstractParser<Endpoint>() {
      public Endpoint parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Endpoint(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Endpoint> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ENDPOINT_FIELD_NUMBER = 1;
    private java.lang.Object endpoint_;
    /**
     * <code>optional string endpoint = 1;</code>
     */
    public boolean hasEndpoint() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string endpoint = 1;</code>
     */
    public java.lang.String getEndpoint() {
      java.lang.Object ref = endpoint_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          endpoint_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string endpoint = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEndpointBytes() {
      java.lang.Object ref = endpoint_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endpoint_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private java.lang.Object value_;
    /**
     * <code>optional string value = 2;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string value = 2;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string value = 2;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      endpoint_ = "";
      value_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getEndpointBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getValueBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getEndpointBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static fr.membrives.etienne.remote.RemoteProtos.Endpoint parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Endpoint parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Endpoint parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Endpoint parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Endpoint parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Endpoint parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Endpoint parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Endpoint parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Endpoint parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Endpoint parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(fr.membrives.etienne.remote.RemoteProtos.Endpoint prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Endpoint}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Endpoint)
        fr.membrives.etienne.remote.RemoteProtos.EndpointOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fr.membrives.etienne.remote.RemoteProtos.internal_static_proto_Endpoint_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fr.membrives.etienne.remote.RemoteProtos.internal_static_proto_Endpoint_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fr.membrives.etienne.remote.RemoteProtos.Endpoint.class, fr.membrives.etienne.remote.RemoteProtos.Endpoint.Builder.class);
      }

      // Construct using fr.membrives.etienne.remote.RemoteProtos.Endpoint.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        endpoint_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fr.membrives.etienne.remote.RemoteProtos.internal_static_proto_Endpoint_descriptor;
      }

      public fr.membrives.etienne.remote.RemoteProtos.Endpoint getDefaultInstanceForType() {
        return fr.membrives.etienne.remote.RemoteProtos.Endpoint.getDefaultInstance();
      }

      public fr.membrives.etienne.remote.RemoteProtos.Endpoint build() {
        fr.membrives.etienne.remote.RemoteProtos.Endpoint result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public fr.membrives.etienne.remote.RemoteProtos.Endpoint buildPartial() {
        fr.membrives.etienne.remote.RemoteProtos.Endpoint result = new fr.membrives.etienne.remote.RemoteProtos.Endpoint(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.endpoint_ = endpoint_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fr.membrives.etienne.remote.RemoteProtos.Endpoint) {
          return mergeFrom((fr.membrives.etienne.remote.RemoteProtos.Endpoint)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fr.membrives.etienne.remote.RemoteProtos.Endpoint other) {
        if (other == fr.membrives.etienne.remote.RemoteProtos.Endpoint.getDefaultInstance()) return this;
        if (other.hasEndpoint()) {
          bitField0_ |= 0x00000001;
          endpoint_ = other.endpoint_;
          onChanged();
        }
        if (other.hasValue()) {
          bitField0_ |= 0x00000002;
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        fr.membrives.etienne.remote.RemoteProtos.Endpoint parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (fr.membrives.etienne.remote.RemoteProtos.Endpoint) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object endpoint_ = "";
      /**
       * <code>optional string endpoint = 1;</code>
       */
      public boolean hasEndpoint() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string endpoint = 1;</code>
       */
      public java.lang.String getEndpoint() {
        java.lang.Object ref = endpoint_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            endpoint_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string endpoint = 1;</code>
       */
      public com.google.protobuf.ByteString
          getEndpointBytes() {
        java.lang.Object ref = endpoint_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          endpoint_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string endpoint = 1;</code>
       */
      public Builder setEndpoint(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        endpoint_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string endpoint = 1;</code>
       */
      public Builder clearEndpoint() {
        bitField0_ = (bitField0_ & ~0x00000001);
        endpoint_ = getDefaultInstance().getEndpoint();
        onChanged();
        return this;
      }
      /**
       * <code>optional string endpoint = 1;</code>
       */
      public Builder setEndpointBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        endpoint_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>optional string value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.Endpoint)
    }

    static {
      defaultInstance = new Endpoint(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.Endpoint)
  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string error_message = 1;</code>
     */
    boolean hasErrorMessage();
    /**
     * <code>optional string error_message = 1;</code>
     */
    java.lang.String getErrorMessage();
    /**
     * <code>optional string error_message = 1;</code>
     */
    com.google.protobuf.ByteString
        getErrorMessageBytes();

    /**
     * <code>repeated .proto.Endpoint endpoints = 2;</code>
     */
    java.util.List<fr.membrives.etienne.remote.RemoteProtos.Endpoint> 
        getEndpointsList();
    /**
     * <code>repeated .proto.Endpoint endpoints = 2;</code>
     */
    fr.membrives.etienne.remote.RemoteProtos.Endpoint getEndpoints(int index);
    /**
     * <code>repeated .proto.Endpoint endpoints = 2;</code>
     */
    int getEndpointsCount();
    /**
     * <code>repeated .proto.Endpoint endpoints = 2;</code>
     */
    java.util.List<? extends fr.membrives.etienne.remote.RemoteProtos.EndpointOrBuilder> 
        getEndpointsOrBuilderList();
    /**
     * <code>repeated .proto.Endpoint endpoints = 2;</code>
     */
    fr.membrives.etienne.remote.RemoteProtos.EndpointOrBuilder getEndpointsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto.Response}
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.Response)
      ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Response(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }

    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              errorMessage_ = bs;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                endpoints_ = new java.util.ArrayList<fr.membrives.etienne.remote.RemoteProtos.Endpoint>();
                mutable_bitField0_ |= 0x00000002;
              }
              endpoints_.add(input.readMessage(fr.membrives.etienne.remote.RemoteProtos.Endpoint.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          endpoints_ = java.util.Collections.unmodifiableList(endpoints_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fr.membrives.etienne.remote.RemoteProtos.internal_static_proto_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fr.membrives.etienne.remote.RemoteProtos.internal_static_proto_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fr.membrives.etienne.remote.RemoteProtos.Response.class, fr.membrives.etienne.remote.RemoteProtos.Response.Builder.class);
    }

    public static com.google.protobuf.Parser<Response> PARSER =
        new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ERROR_MESSAGE_FIELD_NUMBER = 1;
    private java.lang.Object errorMessage_;
    /**
     * <code>optional string error_message = 1;</code>
     */
    public boolean hasErrorMessage() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string error_message = 1;</code>
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorMessage_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string error_message = 1;</code>
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENDPOINTS_FIELD_NUMBER = 2;
    private java.util.List<fr.membrives.etienne.remote.RemoteProtos.Endpoint> endpoints_;
    /**
     * <code>repeated .proto.Endpoint endpoints = 2;</code>
     */
    public java.util.List<fr.membrives.etienne.remote.RemoteProtos.Endpoint> getEndpointsList() {
      return endpoints_;
    }
    /**
     * <code>repeated .proto.Endpoint endpoints = 2;</code>
     */
    public java.util.List<? extends fr.membrives.etienne.remote.RemoteProtos.EndpointOrBuilder> 
        getEndpointsOrBuilderList() {
      return endpoints_;
    }
    /**
     * <code>repeated .proto.Endpoint endpoints = 2;</code>
     */
    public int getEndpointsCount() {
      return endpoints_.size();
    }
    /**
     * <code>repeated .proto.Endpoint endpoints = 2;</code>
     */
    public fr.membrives.etienne.remote.RemoteProtos.Endpoint getEndpoints(int index) {
      return endpoints_.get(index);
    }
    /**
     * <code>repeated .proto.Endpoint endpoints = 2;</code>
     */
    public fr.membrives.etienne.remote.RemoteProtos.EndpointOrBuilder getEndpointsOrBuilder(
        int index) {
      return endpoints_.get(index);
    }

    private void initFields() {
      errorMessage_ = "";
      endpoints_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getErrorMessageBytes());
      }
      for (int i = 0; i < endpoints_.size(); i++) {
        output.writeMessage(2, endpoints_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getErrorMessageBytes());
      }
      for (int i = 0; i < endpoints_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, endpoints_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static fr.membrives.etienne.remote.RemoteProtos.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fr.membrives.etienne.remote.RemoteProtos.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(fr.membrives.etienne.remote.RemoteProtos.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Response)
        fr.membrives.etienne.remote.RemoteProtos.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fr.membrives.etienne.remote.RemoteProtos.internal_static_proto_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fr.membrives.etienne.remote.RemoteProtos.internal_static_proto_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fr.membrives.etienne.remote.RemoteProtos.Response.class, fr.membrives.etienne.remote.RemoteProtos.Response.Builder.class);
      }

      // Construct using fr.membrives.etienne.remote.RemoteProtos.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getEndpointsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        errorMessage_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (endpointsBuilder_ == null) {
          endpoints_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          endpointsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fr.membrives.etienne.remote.RemoteProtos.internal_static_proto_Response_descriptor;
      }

      public fr.membrives.etienne.remote.RemoteProtos.Response getDefaultInstanceForType() {
        return fr.membrives.etienne.remote.RemoteProtos.Response.getDefaultInstance();
      }

      public fr.membrives.etienne.remote.RemoteProtos.Response build() {
        fr.membrives.etienne.remote.RemoteProtos.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public fr.membrives.etienne.remote.RemoteProtos.Response buildPartial() {
        fr.membrives.etienne.remote.RemoteProtos.Response result = new fr.membrives.etienne.remote.RemoteProtos.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.errorMessage_ = errorMessage_;
        if (endpointsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            endpoints_ = java.util.Collections.unmodifiableList(endpoints_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.endpoints_ = endpoints_;
        } else {
          result.endpoints_ = endpointsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fr.membrives.etienne.remote.RemoteProtos.Response) {
          return mergeFrom((fr.membrives.etienne.remote.RemoteProtos.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fr.membrives.etienne.remote.RemoteProtos.Response other) {
        if (other == fr.membrives.etienne.remote.RemoteProtos.Response.getDefaultInstance()) return this;
        if (other.hasErrorMessage()) {
          bitField0_ |= 0x00000001;
          errorMessage_ = other.errorMessage_;
          onChanged();
        }
        if (endpointsBuilder_ == null) {
          if (!other.endpoints_.isEmpty()) {
            if (endpoints_.isEmpty()) {
              endpoints_ = other.endpoints_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureEndpointsIsMutable();
              endpoints_.addAll(other.endpoints_);
            }
            onChanged();
          }
        } else {
          if (!other.endpoints_.isEmpty()) {
            if (endpointsBuilder_.isEmpty()) {
              endpointsBuilder_.dispose();
              endpointsBuilder_ = null;
              endpoints_ = other.endpoints_;
              bitField0_ = (bitField0_ & ~0x00000002);
              endpointsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getEndpointsFieldBuilder() : null;
            } else {
              endpointsBuilder_.addAllMessages(other.endpoints_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        fr.membrives.etienne.remote.RemoteProtos.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (fr.membrives.etienne.remote.RemoteProtos.Response) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object errorMessage_ = "";
      /**
       * <code>optional string error_message = 1;</code>
       */
      public boolean hasErrorMessage() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string error_message = 1;</code>
       */
      public java.lang.String getErrorMessage() {
        java.lang.Object ref = errorMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errorMessage_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string error_message = 1;</code>
       */
      public com.google.protobuf.ByteString
          getErrorMessageBytes() {
        java.lang.Object ref = errorMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string error_message = 1;</code>
       */
      public Builder setErrorMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        errorMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string error_message = 1;</code>
       */
      public Builder clearErrorMessage() {
        bitField0_ = (bitField0_ & ~0x00000001);
        errorMessage_ = getDefaultInstance().getErrorMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string error_message = 1;</code>
       */
      public Builder setErrorMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        errorMessage_ = value;
        onChanged();
        return this;
      }

      private java.util.List<fr.membrives.etienne.remote.RemoteProtos.Endpoint> endpoints_ =
        java.util.Collections.emptyList();
      private void ensureEndpointsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          endpoints_ = new java.util.ArrayList<fr.membrives.etienne.remote.RemoteProtos.Endpoint>(endpoints_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          fr.membrives.etienne.remote.RemoteProtos.Endpoint, fr.membrives.etienne.remote.RemoteProtos.Endpoint.Builder, fr.membrives.etienne.remote.RemoteProtos.EndpointOrBuilder> endpointsBuilder_;

      /**
       * <code>repeated .proto.Endpoint endpoints = 2;</code>
       */
      public java.util.List<fr.membrives.etienne.remote.RemoteProtos.Endpoint> getEndpointsList() {
        if (endpointsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(endpoints_);
        } else {
          return endpointsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.Endpoint endpoints = 2;</code>
       */
      public int getEndpointsCount() {
        if (endpointsBuilder_ == null) {
          return endpoints_.size();
        } else {
          return endpointsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.Endpoint endpoints = 2;</code>
       */
      public fr.membrives.etienne.remote.RemoteProtos.Endpoint getEndpoints(int index) {
        if (endpointsBuilder_ == null) {
          return endpoints_.get(index);
        } else {
          return endpointsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.Endpoint endpoints = 2;</code>
       */
      public Builder setEndpoints(
          int index, fr.membrives.etienne.remote.RemoteProtos.Endpoint value) {
        if (endpointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEndpointsIsMutable();
          endpoints_.set(index, value);
          onChanged();
        } else {
          endpointsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Endpoint endpoints = 2;</code>
       */
      public Builder setEndpoints(
          int index, fr.membrives.etienne.remote.RemoteProtos.Endpoint.Builder builderForValue) {
        if (endpointsBuilder_ == null) {
          ensureEndpointsIsMutable();
          endpoints_.set(index, builderForValue.build());
          onChanged();
        } else {
          endpointsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Endpoint endpoints = 2;</code>
       */
      public Builder addEndpoints(fr.membrives.etienne.remote.RemoteProtos.Endpoint value) {
        if (endpointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEndpointsIsMutable();
          endpoints_.add(value);
          onChanged();
        } else {
          endpointsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Endpoint endpoints = 2;</code>
       */
      public Builder addEndpoints(
          int index, fr.membrives.etienne.remote.RemoteProtos.Endpoint value) {
        if (endpointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEndpointsIsMutable();
          endpoints_.add(index, value);
          onChanged();
        } else {
          endpointsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Endpoint endpoints = 2;</code>
       */
      public Builder addEndpoints(
          fr.membrives.etienne.remote.RemoteProtos.Endpoint.Builder builderForValue) {
        if (endpointsBuilder_ == null) {
          ensureEndpointsIsMutable();
          endpoints_.add(builderForValue.build());
          onChanged();
        } else {
          endpointsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Endpoint endpoints = 2;</code>
       */
      public Builder addEndpoints(
          int index, fr.membrives.etienne.remote.RemoteProtos.Endpoint.Builder builderForValue) {
        if (endpointsBuilder_ == null) {
          ensureEndpointsIsMutable();
          endpoints_.add(index, builderForValue.build());
          onChanged();
        } else {
          endpointsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Endpoint endpoints = 2;</code>
       */
      public Builder addAllEndpoints(
          java.lang.Iterable<? extends fr.membrives.etienne.remote.RemoteProtos.Endpoint> values) {
        if (endpointsBuilder_ == null) {
          ensureEndpointsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, endpoints_);
          onChanged();
        } else {
          endpointsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Endpoint endpoints = 2;</code>
       */
      public Builder clearEndpoints() {
        if (endpointsBuilder_ == null) {
          endpoints_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          endpointsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.Endpoint endpoints = 2;</code>
       */
      public Builder removeEndpoints(int index) {
        if (endpointsBuilder_ == null) {
          ensureEndpointsIsMutable();
          endpoints_.remove(index);
          onChanged();
        } else {
          endpointsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Endpoint endpoints = 2;</code>
       */
      public fr.membrives.etienne.remote.RemoteProtos.Endpoint.Builder getEndpointsBuilder(
          int index) {
        return getEndpointsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.Endpoint endpoints = 2;</code>
       */
      public fr.membrives.etienne.remote.RemoteProtos.EndpointOrBuilder getEndpointsOrBuilder(
          int index) {
        if (endpointsBuilder_ == null) {
          return endpoints_.get(index);  } else {
          return endpointsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.Endpoint endpoints = 2;</code>
       */
      public java.util.List<? extends fr.membrives.etienne.remote.RemoteProtos.EndpointOrBuilder> 
           getEndpointsOrBuilderList() {
        if (endpointsBuilder_ != null) {
          return endpointsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(endpoints_);
        }
      }
      /**
       * <code>repeated .proto.Endpoint endpoints = 2;</code>
       */
      public fr.membrives.etienne.remote.RemoteProtos.Endpoint.Builder addEndpointsBuilder() {
        return getEndpointsFieldBuilder().addBuilder(
            fr.membrives.etienne.remote.RemoteProtos.Endpoint.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.Endpoint endpoints = 2;</code>
       */
      public fr.membrives.etienne.remote.RemoteProtos.Endpoint.Builder addEndpointsBuilder(
          int index) {
        return getEndpointsFieldBuilder().addBuilder(
            index, fr.membrives.etienne.remote.RemoteProtos.Endpoint.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.Endpoint endpoints = 2;</code>
       */
      public java.util.List<fr.membrives.etienne.remote.RemoteProtos.Endpoint.Builder> 
           getEndpointsBuilderList() {
        return getEndpointsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          fr.membrives.etienne.remote.RemoteProtos.Endpoint, fr.membrives.etienne.remote.RemoteProtos.Endpoint.Builder, fr.membrives.etienne.remote.RemoteProtos.EndpointOrBuilder> 
          getEndpointsFieldBuilder() {
        if (endpointsBuilder_ == null) {
          endpointsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              fr.membrives.etienne.remote.RemoteProtos.Endpoint, fr.membrives.etienne.remote.RemoteProtos.Endpoint.Builder, fr.membrives.etienne.remote.RemoteProtos.EndpointOrBuilder>(
                  endpoints_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          endpoints_ = null;
        }
        return endpointsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:proto.Response)
    }

    static {
      defaultInstance = new Response(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.Response)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Endpoint_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_Endpoint_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\005proto\"S\n\007Request\022 \n\004typ" +
      "e\030\001 \001(\0162\022.proto.RequestType\022&\n\rwrite_req" +
      "uest\030\002 \003(\0132\017.proto.Endpoint\"+\n\010Endpoint\022" +
      "\020\n\010endpoint\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\"E\n\010Resp" +
      "onse\022\025\n\rerror_message\030\001 \001(\t\022\"\n\tendpoints" +
      "\030\002 \003(\0132\017.proto.Endpoint*8\n\013RequestType\022\025" +
      "\n\021SERVICE_DISCOVERY\020\001\022\022\n\016WRITE_ENDPOINT\020" +
      "\002B+\n\033fr.membrives.etienne.remoteB\014Remote" +
      "Protos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_Request_descriptor,
        new java.lang.String[] { "Type", "WriteRequest", });
    internal_static_proto_Endpoint_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_Endpoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_Endpoint_descriptor,
        new java.lang.String[] { "Endpoint", "Value", });
    internal_static_proto_Response_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_Response_descriptor,
        new java.lang.String[] { "ErrorMessage", "Endpoints", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
